### ISSUE TITLE
코드 수정 요청 사항(2)

### ISSUE THREAD

**Issue by snoopspy** [hwanj-95/send-arp#2]
### Mac 크기 값 통일
main.cpp 파일에서 mac address 처리를 위하여 사용되는 memset, memcpy 함수의 3번째 인자(6)에 여러가지가 혼용되어 사용되고 있습니다. 통일시켜 주시기 바랍니다.
```
ETHER_ADDR_LEN
sizeof(mac_addr)
sizeof(ReqReppacket.eth.ether_dhost)
sizeof(ReqReppacket.arp.tmac)
```

### 불필요한 파일 삭제
send-arp.pro.user 파일은 git에서 삭제해 주시기 바랍니다.

**Comment by hwanj-95** [comment]
done in https://github.com/hwanj-95/send-arp/commit/310590e261547edfb936ea4f016add73a9199b6e https://github.com/hwanj-95/send-arp/commit/8d4227fe933bd8181120e3fd714e9f60377986e9

**Comment by hwanj-95** [comment]
수정 완료했습니다. 그리고 send-arp.pro.user 파일도 git에서 삭제했습니다.https://github.com/hwanj-95/send-arp/issues/2 Windows 10용 메일에서 보냄 보낸 사람: Gilbert Lee보낸 날짜: 2020년 4월 23일 목요일 오후 7:31받는 사람: hwanj-95/send-arp참조: Subscribed제목: [hwanj-95/send-arp] 코드 수정 요청 사항 (#2) main.cpp 파일에서 mac address 처리를 위하여 사용되는 memset, memcpy 함수의 3번째 인자(6)에 여러가지가 혼용되어 사용되고 있습니다. 통일시켜 주시기 바랍니다.ETHER_ADDR_LENsizeof(mac_addr)sizeof(ReqReppacket.eth.ether_dhost)sizeof(ReqReppacket.arp.tmac)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by snoopspy** [comment]
수고하셨습니다.
